# Generated by Django 5.1.4 on 2026-05-12 15:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("file", models.FileField(upload_to="assets/%Y/%m/")),
                ("mime", models.CharField(max_length=100)),
                ("size", models.BigIntegerField()),
                ("width", models.IntegerField(default=0)),
                ("height", models.IntegerField(default=0)),
                ("duration_ms", models.IntegerField(default=0)),
                ("sha256", models.CharField(db_index=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "media_asset",
            },
        ),
    ]
