# Generated by Django 5.1.4 on 2026-05-12 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0002_bookmark"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="bookmark",
            new_name="feeds_bookm_user_id_78ec50_idx",
            old_name="feeds_bookm_user_id_at_idx",
        ),
    ]
