# Generated by Django 5.1.4 on 2026-05-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "feeds",
            "0003_rename_feeds_bookm_user_id_at_idx_feeds_bookm_user_id_78ec50_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="allow_comments",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="post",
            name="allow_sharing",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="post",
            name="hide_comments",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="hide_likes",
            field=models.BooleanField(default=False),
        ),
    ]
